# non ocr
# CUDA_VISIBLE_DEVICES=3 python tools/llava_tools/llava_infer.py data/vd-instruct-2/test/instructdoc_llava_funsd.json data/vd-instruct-2/infer/instructdoc_llava_funsd.json --model_path checkpoints/llava-v1.6-vicuna-7b-instrucdoc-full-lora-1e4 --model_base liuhaotian/llava-v1.6-vicuna-7b
# CUDA_VISIBLE_DEVICES=3 python tools/llava_tools/llava_infer.py data/vd-instruct-2/test/instructdoc_llava_cord.json data/vd-instruct-2/infer/instructdoc_llava_cord.json --model_path checkpoints/llava-v1.6-vicuna-7b-instrucdoc-full-lora-1e4 --model_base liuhaotian/llava-v1.6-vicuna-7b
# CUDA_VISIBLE_DEVICES=3 python tools/llava_tools/llava_infer.py data/vd-instruct-2/test/instructdoc_llava_chartqa.json data/vd-instruct-2/infer/instructdoc_llava_chartqa.json --model_path checkpoints/llava-v1.6-vicuna-7b-instrucdoc-full-lora-1e4 --model_base liuhaotian/llava-v1.6-vicuna-7b
# CUDA_VISIBLE_DEVICES=3 python tools/llava_tools/llava_infer.py data/vd-instruct-2/test/instructdoc_llava_infovqa.json data/vd-instruct-2/infer/instructdoc_llava_infovqa.json --model_path checkpoints/llava-v1.6-vicuna-7b-instrucdoc-full-lora-1e4 --model_base liuhaotian/llava-v1.6-vicuna-7b
# CUDA_VISIBLE_DEVICES=3 python tools/llava_tools/llava_infer.py data/vd-instruct-2/test/instructdoc_llava_tabfact.json data/vd-instruct-2/infer/instructdoc_llava_tabfact.json --model_path checkpoints/llava-v1.6-vicuna-7b-instrucdoc-full-lora-1e4 --model_base liuhaotian/llava-v1.6-vicuna-7b
# CUDA_VISIBLE_DEVICES=3 python tools/llava_tools/llava_infer.py data/vd-instruct-2/test/instructdoc_llava_dude.json data/vd-instruct-2/infer/instructdoc_llava_dude.json --model_path checkpoints/llava-v1.6-vicuna-7b-instrucdoc-full-lora-1e4 --model_base liuhaotian/llava-v1.6-vicuna-7b
# CUDA_VISIBLE_DEVICES=3 python tools/llava_tools/llava_infer.py data/vd-instruct-2/test/instructdoc_llava_slidevqa.json data/vd-instruct-2/infer/instructdoc_llava_slidevqa.json --model_path checkpoints/llava-v1.6-vicuna-7b-instrucdoc-full-lora-1e4 --model_base liuhaotian/llava-v1.6-vicuna-7b

# ocr
# CUDA_VISIBLE_DEVICES=0,1,3,4 python /mnt/KAIST/son/LLaVA-Doc/llava/eval/instructdoc_infer.py /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/test/no-ocr/instructdoc_llava_funsd.json /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/infer/no-ocr/instructdoc_llava_13b_funsd.json --model_path checkpoints/llava-v1.6-vicuna-13b-instrucdoc-full-lora-1e4-no-ocr --model_base liuhaotian/llava-v1.6-vicuna-13b
# CUDA_VISIBLE_DEVICES=0,1,3,4 python /mnt/KAIST/son/LLaVA-Doc/llava/eval/instructdoc_infer.py /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/test/no-ocr/instructdoc_llava_cord.json /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/infer/no-ocr/instructdoc_llava_13b_cord.json --model_path checkpoints/llava-v1.6-vicuna-13b-instrucdoc-full-lora-1e4-no-ocr --model_base liuhaotian/llava-v1.6-vicuna-13b
# CUDA_VISIBLE_DEVICES=0,1,3,4 python /mnt/KAIST/son/LLaVA-Doc/llava/eval/instructdoc_infer.py /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/test/no-ocr/instructdoc_llava_chartqa.json /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/infer/no-ocr/instructdoc_llava_13b_chartqa.json --model_path checkpoints/llava-v1.6-vicuna-13b-instrucdoc-full-lora-1e4-no-ocr --model_base liuhaotian/llava-v1.6-vicuna-13b
# CUDA_VISIBLE_DEVICES=0,1,3,4 python /mnt/KAIST/son/LLaVA-Doc/llava/eval/instructdoc_infer.py /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/test/no-ocr/instructdoc_llava_infovqa.json /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/infer/no-ocr/instructdoc_llava_13b_infovqa.json --model_path checkpoints/llava-v1.6-vicuna-13b-instrucdoc-full-lora-1e4-no-ocr --model_base liuhaotian/llava-v1.6-vicuna-13b
# CUDA_VISIBLE_DEVICES=0,1,3,4 python /mnt/KAIST/son/LLaVA-Doc/llava/eval/instructdoc_infer.py /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/test/no-ocr/instructdoc_llava_tabfact.json /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/infer/no-ocr/instructdoc_llava_13b_tabfact.json --model_path checkpoints/llava-v1.6-vicuna-13b-instrucdoc-full-lora-1e4-no-ocr --model_base liuhaotian/llava-v1.6-vicuna-13b
# CUDA_VISIBLE_DEVICES=0,1,3,4 python /mnt/KAIST/son/LLaVA-Doc/llava/eval/instructdoc_infer.py /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/test/no-ocr/instructdoc_llava_dude.json /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/infer/no-ocr/instructdoc_llava_13b_dude.json --model_path checkpoints/llava-v1.6-vicuna-13b-instrucdoc-full-lora-1e4-no-ocr --model_base liuhaotian/llava-v1.6-vicuna-13b
# CUDA_VISIBLE_DEVICES=0,1,3,4 python /mnt/KAIST/son/LLaVA-Doc/llava/eval/instructdoc_infer.py /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/test/no-ocr/instructdoc_llava_slidevqa.json /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/infer/no-ocr/instructdoc_llava_13b_slidevqa.json --model_path checkpoints/llava-v1.6-vicuna-13b-instrucdoc-full-lora-1e4-no-ocr --model_base liuhaotian/llava-v1.6-vicuna-13b

CUDA_VISIBLE_DEVICES=3,4 python /mnt/KAIST/son/LLaVA-Doc/llava/eval/instructdoc_infer.py /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/test/no-ocr/instructdoc_llava_funsd.json /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/infer/no-ocr/instructdoc_llavar_funsd.json --model_path checkpoints/llavar-v1-instrucdoc-full-lora-1e4-no-ocr --model_base truehealth/LLaVar
CUDA_VISIBLE_DEVICES=3,4 python /mnt/KAIST/son/LLaVA-Doc/llava/eval/instructdoc_infer.py /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/test/no-ocr/instructdoc_llava_cord.json /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/infer/no-ocr/instructdoc_llavar_cord.json --model_path checkpoints/llavar-v1-instrucdoc-full-lora-1e4-no-ocr --model_base truehealth/LLaVar
CUDA_VISIBLE_DEVICES=3,4 python /mnt/KAIST/son/LLaVA-Doc/llava/eval/instructdoc_infer.py /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/test/no-ocr/instructdoc_llava_chartqa.json /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/infer/no-ocr/instructdoc_llavar_chartqa.json --model_path checkpoints/llavar-v1-instrucdoc-full-lora-1e4-no-ocr --model_base truehealth/LLaVar
CUDA_VISIBLE_DEVICES=3,4 python /mnt/KAIST/son/LLaVA-Doc/llava/eval/instructdoc_infer.py /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/test/no-ocr/instructdoc_llava_infovqa.json /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/infer/no-ocr/instructdoc_llavar_infovqa.json --model_path checkpoints/llavar-v1-instrucdoc-full-lora-1e4-no-ocr --model_base truehealth/LLaVar
# CUDA_VISIBLE_DEVICES=0,1,3,4 python /mnt/KAIST/son/LLaVA-Doc/llava/eval/instructdoc_infer.py /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/test/no-ocr/instructdoc_llava_tabfact.json /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/infer/no-ocr/instructdoc_llavar_tabfact.json --model_path checkpoints/llavar-instrucdoc-full-lora-1e4-no-ocr --model_base truehealth/LLaVar
# CUDA_VISIBLE_DEVICES=0,1,3,4 python /mnt/KAIST/son/LLaVA-Doc/llava/eval/instructdoc_infer.py /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/test/no-ocr/instructdoc_llava_dude.json /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/infer/no-ocr/instructdoc_llavar_dude.json --model_path checkpoints/llavar-instrucdoc-full-lora-1e4-no-ocr --model_base truehealth/LLaVar
# CUDA_VISIBLE_DEVICES=0,1,3,4 python /mnt/KAIST/son/LLaVA-Doc/llava/eval/instructdoc_infer.py /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/test/no-ocr/instructdoc_llava_slidevqa.json /mnt/KAIST/son/VD-Instruct/data/vd-instruct-2/infer/no-ocr/instructdoc_llavar_slidevqa.json --model_path checkpoints/llavar-instrucdoc-full-lora-1e4-no-ocr --model_base truehealth/LLaVar
